# Site settings
site: dimonaco.dev
title: Carmine Di Monaco - computing pizza
keywords: blog, carmine, di monaco, programming
description: >-
  dimonaco.dev - Carmine Di Monaco personal site and blog
lang: en-US
timezone:  Europe/Rome

# Author settings
author:
  name: Carmine Di Monaco
  bio: Senior Software Engineer @ SUSE <br />  Podcast Speaker @ <a href="https://gitbar.it"> Gitbar </a> <br /> golang, elixir, rust, node and pizza
  picture: assets/images/profile.jpg 
  github: CDimonaco # github username
  twitter: CDimonaco # twitter username
  linkedin: carmine-di-monaco # linkedin username
  email: carmine.dimonaco@gmail.com # email adress


# URL settings
url: "http://127.0.0.1:4000" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false